### PR TITLE
Subclass RasterFootprint to reduce memory requirements

### PR DESCRIPTION
**Pull request by pjhartzell**
**Related Issue(s):**
None.

**Description:**
ESA WorldCover tiles are large (36000x36000 pixels), causing the numpy-based mask computation in the stactools RasterFootprint class to consume >30GB for some tiles. This is more than many machines support. I subclassed RasterFootprint to operate directly on a mask array produced by rasterio, which does have large memory requirements. 

This is a workaround for an eventual change to RasterFootprint in stactools to default to using rasterio's mask when it is available.

I don't _think_ this requires a changelog entry since the API used to interact with the STAC hasn't changed (unless you count the existence of the new utility class).

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [x] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Examples have been updated to reflect changes, if applicable
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

### CODE REVIEW

**Review by gadomski — APPROVED** [review]
LGTM. Did you like the experience of subclassing the raster footprint? This is a good check on the design of the `RasterFootprint` class.

**Comment by pjhartzell** [comment]
>LGTM. Did you like the experience of subclassing the raster footprint? This is a good check on the design of the RasterFootprint class.

The presence of the alternative constructors can be a PITA. In this case, if you call `from_href()`, this subclass is not going to work, because `from_href()` feeds the initializer the raster data array, not the mask array. I'm not using any alternative constructors, so I didn't bother overriding the necessary methods...but maybe I should?

**Comment by gadomski** [comment]
>  In this case, if you use from_href(), footprint generation is not going to work, because from_href() feeds the initializer the raster data array, not the mask array.

Hm, that's interesting, and is _a bit_ of a smell. I'd say that dummying out `data_mask` is a bit of a smell too -- feels like there's an operation that should be abstracted away there, but I'm not deep enough in the space to know what at the moment.

There _could_ be an opportunity to spike this into a refactor of `RasterFootprint` to better match this customization case, but I don't think that's required -- feels like we've got an 80% solution with what we have at the moment.

> I'm not using any alternative constructors, so I didn't bother overriding the necessary methods...but maybe I should?

🤷🏽 I think stactools-packages are specific enough that we can safely assume no one will inherit from them, so fully protecting the API of `ESAWorldCoverFootprint` isn't required.

**Comment by pjhartzell** [comment]
>There could be an opportunity to spike this into a refactor of RasterFootprint to better match this customization case,

Given what I now know about performance of rasterio's masks versus custom computation thereof, we should probably be using rasterio masks by default. Only compute a custom mask when a `nodata` value is specified and does not match the value in the file. That would eliminate the need for a custom class here.

**Pull request merged**
